name: CI workflow of ginkgo leaf

on: [push] process of ginkgo leaf

jobs:make process of ginkgo leaf
  build:dpcpp

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: dpcpp
        echo Add other actions to build,
        echo test, and deploy your project.
